export const customStyles = {
  control: (baseStyles, state) => ({
    ...baseStyles,
    backgroundColor: "black",
    width: "calc(100vw - 45px)",
    height: "54px",
    border: "1px solid #050505",
    boxShadow: "0px 0px 10px 1px #ffffff",
    borderRadius: "10px",
    color: "white",
    paddingLeft: "45px",
  }),
  option: (baseStyles, state) => ({
    ...baseStyles,
    fontFamily: "JetBrains Mono",
    fontWeight: "400",
    fontSize: "13px",
    lineHeight: "17px",
    color: state.isSelected ? "black" : "white",
    backgroundColor: state.isSelected ? "white" : "black",
    borderRadius: "10px",
  }),
  singleValue: (baseStyles, state) => ({
    ...baseStyles,
    fontFamily: "JetBrains Mono",
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: "17px",
    textAlign: "center",
    color: "white",
    fontSize: "16px",
  }),
  placeholder: (baseStyles, state) => ({
    ...baseStyles,
    fontFamily: "JetBrains Mono",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: "13px",
    lineHeight: "17px",
    display: "flex",
    alignItems: "center",
    textAlign: "center",
    color: "white",
  }),
  menu: (baseStyles, state) => ({
    ...baseStyles,
    backgroundColor: "black",
    borderRadius: "10px",
  }),
  input: (baseStyles, state) => ({
    ...baseStyles,
    fontFamily: "JetBrains Mono",
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: "17px",
    textAlign: "center",
    color: "white",
    fontSize: "16px",
    caretСolor: "transparent",
  }),
};
